imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies:
      [172.0.0.0/8]
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

sensio_framework_extra: ~


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        logging:  false
        profiling:  false
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                degrees: DoctrineExtensions\Query\Mysql\Degrees
                acos: DoctrineExtensions\Query\Mysql\Acos
                sin: DoctrineExtensions\Query\Mysql\Sin
                radians: DoctrineExtensions\Query\Mysql\Radians
                cos: DoctrineExtensions\Query\Mysql\Cos
                date_format: Kfc\Bundle\CoreBundle\DQL\DateFormat
                replace: Kfc\Bundle\CoreBundle\DQL\ReplaceFunction
                rand: Kfc\Bundle\CoreBundle\DQL\RandFunction
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
            numeric_functions:
                st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true

    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true


stof_doctrine_extensions:
    orm:
        default:
            tree: true

nelmio_api_doc:
    name: '2gis test documentation'
    motd:
        template: 'DoubleGisTestBundle::Nelmio/motd.html.twig'

fos_http_cache:
    proxy_client:
        varnish:
            servers: varnish
            base_url: laptop
    cache_control:
        defaults:
            overwrite: false
        rules:
            -
                match:
                    path: ^/
                headers:
                    cache_control:
                        public: true
                        max_age: 64000
                        s_maxage: 64000
                    etag: true