DoubleGis\TestBundle\Entity\Category:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    name:
      expose: true
  relations:
      - rel: children
        embedded:
            content: expr(object.getChildren())
        exclusion:
            groups: [tree]