buildings:
    type: rest
    resource: "@DoubleGisTestBundle/Resources/config/routing/buildings.yml"
organizations:
    type: rest
    resource: "@DoubleGisTestBundle/Resources/config/routing/organizations.yml"
categories:
    type: rest
    resource: "@DoubleGisTestBundle/Resources/config/routing/categories.yml"
doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc